import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import PrimaryButton from "@/shared/primaryButton/PrimaryButton";
import FeaturedProducts from "@/components/featuredProducts/FeaturedProducts";
import CollectionSection from "@/components/collectionSection/CollectionSection";
import OurValuesSection from "@/components/ourValuesSection/OurValuesSection";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ womenNewReleases, menNewReleases }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.headerCTA}>
          <h1>WANT 25% OFF ON NEW REALESES?</h1>
          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aperiam
            dolorum veniam iste officia doloremque molestias, aut nihil quidem
            ad hic.
          </p>
          <div>
            <PrimaryButton>SHOP NOW</PrimaryButton>
          </div>
        </div>
      </header>
      <FeaturedProducts newReleases={womenNewReleases} />
      <CollectionSection />
      <FeaturedProducts newReleases={menNewReleases} />
      <CollectionSection />
      <OurValuesSection />
    </>
  );
}

export async function getStaticProps() {
  const response = await fetch(
    "http://127.0.0.1:1337/api/items?populate=image",
    {
      method: "GET",
    }
  );

  const items = await response.json();

  const womenNewReleases = items.data
    .filter((item) => item.attributes.category === "women")
    .slice(0, 4);

  const menNewReleases = items.data
    .filter((item) => item.attributes.category === "men")
    .slice(0, 4);

  return {
    props: { womenNewReleases, menNewReleases },
  };
}
